# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{activerecord-postgres-copy}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Diogo Biazus"]
  s.date = %q{2011-02-07}
  s.description = %q{Now you can use the super fast COPY for import/export data directly from your AR models.}
  s.email = %q{diogob@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "activerecord-postgres-copy.gemspec",
     "lib/activerecord-postgres-copy.rb",
     "lib/activerecord-postgres-copy/base.rb",
     "spec/fixtures/extra_field.rb",
     "spec/fixtures/semicolon_with_header.csv",
     "spec/fixtures/tab_only_data.csv",
     "spec/fixtures/tab_with_header.csv",
     "spec/fixtures/test_model.rb",
     "spec/pg_copy_from_spec.rb",
     "spec/pg_copy_to_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/diogob/activerecord-postgres-copy}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Put COPY command functionality in ActiveRecord's model class}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/pg_copy_from_spec.rb",
     "spec/pg_copy_to_spec.rb",
     "spec/fixtures/test_model.rb",
     "spec/fixtures/extra_field.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

